/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carrinho.glb 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/future-is-our-legacy-18babb7cc04146ada3e3f80c4739d91a
Title: Future is our legacy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Carrinho(props) {
  const { nodes, materials } = useGLTF('/carrinho.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.821}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.301, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.GOLD} />
          </group>
          <group position={[0, -0.816, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} />
          </group>
          <group position={[0, -1.015, 0]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.GOLD} />
          </group>
          <group position={[0, 0.012, 0]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials.GOLD} />
            <mesh geometry={nodes.Object_66.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_67.geometry} material={materials['Material.037']} />
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_69.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_70.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_71.geometry} material={materials['Material.031']} />
            <mesh geometry={nodes.Object_72.geometry} material={materials['Material.034']} />
            <mesh geometry={nodes.Object_73.geometry} material={materials['Material.035']} />
            <mesh geometry={nodes.Object_74.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.Object_75.geometry} material={materials['Material.032']} />
          </group>
          <group position={[0.001, 0.005, -0.002]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025}>
            <group position={[-8.437, 8.469, -0.476]}>
              <group position={[56.225, -0.598, -37.605]} scale={4.808}>
                <mesh geometry={nodes.Object_83.geometry} material={materials.Blanc} />
                <mesh geometry={nodes.Object_84.geometry} material={materials.GOLD} />
              </group>
              <mesh geometry={nodes.Object_79.geometry} material={materials.GOLD} position={[7.707, -0.598, -1.111]} scale={4.808} />
              <mesh geometry={nodes.Object_81.geometry} material={materials.Blanc} position={[7.707, -0.598, -1.111]} scale={4.808} />
            </group>
          </group>
          <group position={[0.001, 0.972, -0.002]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025}>
            <group position={[-8.437, 8.469, -0.476]}>
              <group position={[7.707, -0.598, -1.111]} scale={4.808}>
                <mesh geometry={nodes.Object_90.geometry} material={materials.Material} />
                <mesh geometry={nodes.Object_91.geometry} material={materials['Material.015']} />
              </group>
            </group>
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_97.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_98.geometry} material={materials.GOLD} />
          </group>
          <group position={[0, 0.006, 2.29]} scale={0.938}>
            <mesh geometry={nodes.Object_103.geometry} material={materials.GOLD} />
            <mesh geometry={nodes.Object_104.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_105.geometry} material={materials['Material.037']} />
            <mesh geometry={nodes.Object_106.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_107.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_108.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_109.geometry} material={materials['Material.031']} />
            <mesh geometry={nodes.Object_110.geometry} material={materials['Material.034']} />
            <mesh geometry={nodes.Object_111.geometry} material={materials['Material.035']} />
            <mesh geometry={nodes.Object_112.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.Object_113.geometry} material={materials['Material.032']} />
          </group>
          <group position={[-0.039, -0.419, -1.039]} rotation={[-3.137, 0, 0]} scale={0.259}>
            <mesh geometry={nodes.Object_115.geometry} material={materials['Carosserie.001']} />
            <mesh geometry={nodes.Object_116.geometry} material={materials['Material.023']} />
            <mesh geometry={nodes.Object_117.geometry} material={materials['Blanck.001']} />
            <mesh geometry={nodes.Object_118.geometry} material={materials.CARBONE} />
            <mesh geometry={nodes.Object_119.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_120.geometry} material={materials.Jantes} />
            <mesh geometry={nodes.Object_121.geometry} material={materials['Rouge.001']} />
            <mesh geometry={nodes.Object_122.geometry} material={materials.material_31} />
            <mesh geometry={nodes.Object_123.geometry} material={materials['Orange.001']} />
            <mesh geometry={nodes.Object_124.geometry} material={materials['Sige.001']} />
            <mesh geometry={nodes.Object_125.geometry} material={materials['Vert.001']} />
            <mesh geometry={nodes.Object_126.geometry} material={materials['Blanc.001']} />
            <mesh geometry={nodes.Object_127.geometry} material={materials['Material.039']} />
            <mesh geometry={nodes.Object_128.geometry} material={materials['Material.028']} />
            <mesh geometry={nodes.Object_129.geometry} material={materials['Material.027']} />
            <mesh geometry={nodes.Object_130.geometry} material={materials['Material.042']} />
            <mesh geometry={nodes.Object_131.geometry} material={materials['Material.040']} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.Lumire_rouge} />
            <mesh geometry={nodes.Object_133.geometry} material={materials['Material.029']} />
            <mesh geometry={nodes.Object_134.geometry} material={materials.material_43} />
            <mesh geometry={nodes.Object_135.geometry} material={materials.Vitres} />
            <mesh geometry={nodes.Object_136.geometry} material={materials.Lumire_blanche} />
            <mesh geometry={nodes.Object_137.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Object_138.geometry} material={materials.Volant} />
            <mesh geometry={nodes.Object_139.geometry} material={materials.Jantes_I} />
            <mesh geometry={nodes.Object_140.geometry} material={materials['Material.041']} />
            <mesh geometry={nodes.Object_141.geometry} material={materials.Lumire_Orange} />
          </group>
          <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.005']} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Object_30.geometry} material={materials['Material.009']} position={[0, -0.816, 0]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.GOLD} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Material.005']} position={[0, -0.816, 0]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.GOLD} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.GOLD} />
          <mesh geometry={nodes.Object_45.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_47.geometry} material={materials['Material.004']} position={[0, 4.283, 0]} />
          <mesh geometry={nodes.Object_49.geometry} material={materials['Material.001']} position={[0, 4.283, 0]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.GOLD} position={[0, 17.059, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.216} />
          <mesh geometry={nodes.Object_55.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Object_57.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Object_58.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Object_59.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_61.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.GOLD} />
          <mesh geometry={nodes.Object_63.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Object_86.geometry} material={materials['Material.006']} position={[0, 2.84, 0]} />
          <mesh geometry={nodes.Object_93.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_95.geometry} material={materials.GOLD} position={[0.456, -65.16, 0.343]} scale={0.276} />
          <mesh geometry={nodes.Object_100.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.GOLD} />
          <mesh geometry={nodes.Object_143.geometry} material={materials['Material.043']} scale={13.777} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/carrinho.glb')
